"""specialyties add revision 3

Revision ID: 70716c2fae18
Revises: afb176673f27
Create Date: 2024-12-20 16:25:18.017241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70716c2fae18'
down_revision: Union[str, None] = 'afb176673f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializess',
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('speciality_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('speciality_id')
    )
    op.drop_table('specializes')
    op.add_column('users', sa.Column('spec_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spec_id')
    op.create_table('specializes',
    sa.Column('speciality_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('speciality_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('speciality_id', name='specializess_pkey')
    )
    op.drop_table('specializess')
    # ### end Alembic commands ###
