"""specialyties add revision 2

Revision ID: afb176673f27
Revises: 016d4160d515
Create Date: 2024-12-20 16:03:24.393639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb176673f27'
down_revision: Union[str, None] = '016d4160d515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializess',
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('speciality_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('speciality_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specializess')
    # ### end Alembic commands ###
